USE membership; 
SELECT * From users; 
SELECT * FROM roles; 

INSERT INTO roles (name, permissions) 
VALUES('ROLE_USER', 'READ:USER, READ:CUSTOMER'), 
      ('ROLE:GROUP_LEAD', 'READ:USER,READ:GROUP,UPDATE:GROUP'),
      ('ROLE:GROUP_ADMIN', 'READ:USER,READ:GROUP,UPDATE:GROUP'),
      ('ROLE:MANAGER', 'READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER,READ:GROUP,UPDATE:GROUP,CREATE:GROUP,DELETE:GROUP,CREATE:CUSTOMER,DELETE:CUSTOMER'),
      ('ROLE_ADMIN', 'READ:USER,READ:CUSTOMER,CREATE:USER,CREATE:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER,READ:GROUP,UPDATE:GROUP,CREATE:GROUP,DELETE:GROUP,CREATE:CUSTOMER,DELETE:CUSTOMER'),
      ('ROLE_SYSADMIN', 'READ:USER,READ:CUSTOMER,CREATE:USER,CREATE:CUSTOMER,UPDATE:USER,UPDATE:GROUP,UPDATE:CUSTOMER,DELETE:USER,DELETE:CUSTOMER');
